layout_spectrum: 0.2207304
color:
  saturation: 0.6138561
  brandStrength: 0.3331794
  lightness: 0.7459721
  rhythmicContrast: 0.2486573
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 1
name: Erick Ganem
